### ISSUE TITLE
index out of range error

### ISSUE THREAD

**Issue by ghost** [ivan-krukov/DETECT#1]
Traceback (most recent call last):
  File "/home/j/jparkins/shung/ivan-kryukov-DETECT-cee24eb/detect.py", line 299, in <module>
    identification.hypotheses = run_pair_alignment(seq,blast_db,num_threads,e_value,bit_score)
  File "/home/j/jparkins/shung/ivan-kryukov-DETECT-cee24eb/detect.py", line 132, in run_pair_alignment
    return parse_needle_results(stdout)
  File "/home/j/jparkins/shung/ivan-kryukov-DETECT-cee24eb/detect.py", line 202, in parse_needle_results
    score = float(fields[3][1:-1])
IndexError: list index out of range

**Comment by ivan-krukov** [comment]
This seems to be a problem with `<needle>`.
Can you send me the output from globally aligning some things?
Here is an example: http://www.ncbi.nlm.nih.gov/protein/50540506?report=fasta
`needle -asequence kinase.fasta -bsequence kinase.fasta -gapopen 10 -gapextend 0.5 -aformat_outfile score -stdout -auto`
The report you sent is saying that there is no `<score>` in parentheses as there should be.
